substitutions:
  name: kc868-a4

esphome:
  name: ${name}
  name_add_mac_suffix: true
  
  project:
    name: kincony.kc686-a4
    version: "1"
  
esp32:
  board: esp32dev

# Enable logging
logger:


web_server:
  port: 80
# Enable Home Assistant API
api:

ota:
  password: ""

dashboard_import:
  package_import_url: github://hzkincony/kc868-a4/kc868-a4.yaml@main

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kc868-A4 Fallback Hotspot"
    password: ""

captive_portal:

switch:
  - platform: gpio
    name: "light1"
    pin: 2
    inverted: false

  - platform: gpio
    name: "light2"
    pin: 15
    inverted: false
    
  - platform: gpio
    name: "light3"
    pin: 5
    inverted: false
    
  - platform: gpio
    name: "light4"
    pin: 4
    inverted: false
    
binary_sensor:
  - platform: gpio
    name: "input1"
    pin: 
      number: 36
      inverted: true

  - platform: gpio
    name: "input2"
    pin:
      number: 39
      inverted: true
    
  - platform: gpio
    name: "input3"
    pin:
      number: 27
      inverted: true
      
  - platform: gpio
    name: "input4"
    pin: 
      number: 14
      inverted: true
